language: python
python:
    - "2.7"
install:
    - pip install pandas
    - pip install --no-deps sncosmo
    - python setup.py install --user
script:
    - nosetests -s --with-coverage --cover-package=sncosmo_lc_analysis
